const $ = s => document.querySelector(s);
const DATA = window.MEMORY_WIKI_DATA;
let STATE = { section:'daily', id:null, query:'' };
function esc(v){ return String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function titleCase(s){ return String(s||'').replace(/\b\w/g, m => m.toUpperCase()); }
function compact(text, n=340){ text=String(text||'').replace(/\s+/g,' ').trim(); return text.length>n ? text.slice(0,n-1)+'…' : text; }
function timeOnly(t){ const m=String(t||'').match(/(\d\d:\d\d)/); return m ? m[1] : ''; }
function niceDate(d){ try { return new Date(d+'T00:00:00Z').toLocaleDateString(undefined,{weekday:'long', month:'long', day:'numeric', year:'numeric'}); } catch { return d; } }
function parseHash(){ const h = location.hash.replace(/^#/,''); if(!h) return; const [section, ...rest] = h.split('/'); STATE.section = section || 'daily'; STATE.id = decodeURIComponent(rest.join('/')) || null; }
function go(section,id){ STATE.section=section; STATE.id=id; location.hash = section + (id ? '/' + encodeURIComponent(id) : ''); render(); }
function sessionText(s){ return (s.title+' '+s.asked+' '+s.result).toLowerCase(); }
function passesQuery(s){ return !STATE.query || sessionText(s).includes(STATE.query); }
function buildShell(){
  $('#app').innerHTML = '<aside class="left"><div class="product"><div class="logo">J</div><div><strong>Jarvis</strong><span>Memory Wiki</span></div></div><button class="new-goal" data-go="home">/goal overview</button><label class="search"><span>Search archive</span><input id="q" placeholder="Search work, repos, subjects…"></label><nav><p>Daily logs</p><div id="day-nav"></div><p>Subjects</p><div id="subject-nav"></div></nav><div class="backup-note"><b>Summary-safe Pages</b><span>Full transcripts stay in the private repo; this page opens instantly.</span></div></aside><main class="page"><div class="mobilebar"><button id="hamb">☰</button><b>Memory Wiki</b></div><div id="view"></div></main>';
  $('#day-nav').innerHTML = DATA.daily_logs.map(d => '<button class="navlink" data-kind="daily" data-id="'+esc(d.date)+'"><span>'+esc(d.date)+'</span><small>'+d.session_count+'</small></button>').join('');
  $('#subject-nav').innerHTML = DATA.subjects.map(s => '<button class="navlink" data-kind="subject" data-id="'+esc(s.slug)+'"><span>'+esc(titleCase(s.name))+'</span><small>'+s.count+'</small></button>').join('');
  document.querySelectorAll('.navlink').forEach(b => b.addEventListener('click', () => go(b.dataset.kind, b.dataset.id)));
  $('.new-goal').addEventListener('click', () => go('home',''));
  $('#q').addEventListener('input', e => { STATE.query = e.target.value.toLowerCase().trim(); render(); });
  $('#hamb').addEventListener('click', () => document.body.classList.toggle('menu-open'));
}
function hero(title, eyebrow, subtitle, stats){ return '<section class="hero"><div><div class="mini-label">'+esc(eyebrow)+'</div><h1>'+esc(title)+'</h1><p>'+esc(subtitle)+'</p></div><div class="metric-stack">'+stats.map(x => '<div><b>'+esc(x[0])+'</b><span>'+esc(x[1])+'</span></div>').join('')+'</div></section>'; }
function sessionCard(s){ return '<article class="entry"><div class="entry-time">'+esc(timeOnly(s.started_at))+'</div><div class="entry-body"><div class="entry-head"><div><p class="mini-label">session</p><h3>'+esc(s.title)+'</h3></div><div class="chips"><span>'+s.message_count+' messages</span><span>'+s.tool_call_count+' tools</span></div></div><div class="summary-pair"><section><b>What you asked</b><p>'+esc(compact(s.asked, 360))+'</p></section><section><b>What Jarvis did</b><p>'+esc(compact(s.result, 420))+'</p></section></div></div></article>'; }
function renderHome(){ const latest = DATA.daily_logs[0]; const top = DATA.subjects.slice(0,6); $('#view').innerHTML = hero('Memory command center','/goal overview','A readable dashboard for everything Hemant and Jarvis have worked on together.',[[DATA.daily_logs.length,'daily logs'],[DATA.subjects.length,'subjects'],[DATA.sessions.length,'sessions']]) + '<section class="section-title"><h2>Continue from latest day</h2><button onclick="go(\'daily\',\''+esc(latest.date)+'\')">Open '+esc(latest.date)+'</button></section><div class="subject-grid">'+top.map(s => '<button class="subject-card" onclick="go(\'subject\',\''+esc(s.slug)+'\')"><span>'+s.count+' sessions</span><b>'+esc(titleCase(s.name))+'</b><p>'+esc(compact(s.summary,150))+'</p></button>').join('')+'</div>'; }
function renderDaily(){ if(!STATE.id) STATE.id = DATA.daily_logs[0]?.date; const day = DATA.daily_logs.find(d => d.date===STATE.id) || DATA.daily_logs[0]; const sessions = day.sessions.filter(Boolean).filter(passesQuery); const summary = '<section class="day-summary"><div><p class="mini-label">day summary</p><h2>What happened today</h2><p>'+esc(day.summary || 'Summary will appear after the next rebuild.')+'</p></div><ul>'+((day.highlights||[]).map(h => '<li>'+esc(h)+'</li>').join('') || '<li>No highlights yet.</li>')+'</ul></section>'; $('#view').innerHTML = hero(niceDate(day.date), 'daily log', 'Executive summary first, then readable work cards.', [[sessions.length,'shown'],[day.message_count,'messages'],[day.tool_call_count,'tool calls']]) + summary + '<section class="keywords">'+day.keywords.map(k => '<span>'+esc(k)+'</span>').join('')+'</section><section class="timeline">'+sessions.map(sessionCard).join('')+'</section>'; }
function renderSubject(){ if(!STATE.id) STATE.id = DATA.subjects[0]?.slug; const subject = DATA.subjects.find(s => s.slug===STATE.id) || DATA.subjects[0]; const sessions = subject.sessions.filter(Boolean).filter(passesQuery); $('#view').innerHTML = hero(titleCase(subject.name), 'subject', subject.summary, [[sessions.length,'sessions'],[subject.mentions || subject.count,'mentions']]) + '<section class="timeline compact">'+sessions.map(sessionCard).join('')+'</section>'; }
function render(){ parseHash(); document.querySelectorAll('.navlink').forEach(b => b.classList.toggle('active', b.dataset.kind===STATE.section && b.dataset.id===STATE.id)); if(STATE.section==='home') renderHome(); else if(STATE.section==='subject') renderSubject(); else renderDaily(); document.body.classList.remove('menu-open'); }
function openWiki(){ const pass = $('#pass').value.trim(); if(pass !== 'govind'){ $('#status').textContent = 'Wrong password. Type govind.'; return; } $('#unlock').hidden = true; $('#app').hidden = false; parseHash(); if(!STATE.id && STATE.section==='daily') STATE.id = DATA.daily_logs[0]?.date; buildShell(); render(); }
$('#btn').addEventListener('click', openWiki);
$('#pass').addEventListener('keydown', e => { if(e.key==='Enter') openWiki(); });